In [3]:
import pandas as pd

In [4]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [5]:
df = pd.DataFrame(data, columns = columns)

In [6]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [50]:
df = pd.DataFrame(data)

In [33]:
df.head(3) # returns the first n rows, n = 5 is the default.

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [34]:
# every column of a dataframe is a series. 
df.Make
df["Engine HP"]

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [35]:
# access a subset of the dataframe:
df[["Make", "Model", "MSRP"]]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [36]:
# add a column to a dataframe: 
df['Shamsi Year'] = df['Year'] - 621
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Shamsi Year
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1370
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,1396
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,1389
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,1396
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,1396

In [37]:
# apply method for adding a new column with a function to determine the values:
df['is new'] = df['Year'].apply(lambda x: "Yes" if x > 2011 else "No")
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Shamsi Year,is new
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1370,No
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,1396,Yes
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,1389,No
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,1396,Yes
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,1396,Yes

In [38]:
# add a new column manually: 
df['id'] = [1, 2, 3, 4, 5]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Shamsi Year,is new,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1370,No,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,1396,Yes,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,1389,No,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,1396,Yes,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,1396,Yes,5

In [39]:
# deleting a column / multiple columns from a dataframe:
del df['id']
df.drop(columns=['Shamsi Year', 'is new'], inplace=True)

In [53]:
# each row of a dataframe has an index.
# we access the rows using the index, using the loc method. 
df.loc[[1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [76]:
# when creating a dataframe, we can explicitly determine the indices if we don't want it to be the default (a range from 0 to n-1).
df.index = ['A', 'B', 'C', 'D', 'E']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
A,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
B,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
C,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
D,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
E,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [56]:
# even after changing the default indices, we can access the rows with their positional index using the iloc method:
df.iloc[[1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
B,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
C,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [ ]:
# to get back to the initial indices, we use the reset_index method:
df.reset_index()
# this keeps the previous values as a column called index. if we don't want it, we use drop=True.
df.reset_index(drop=True)
# this method does not change the dataframe. if we want it to do so, we use inplace=True.
df.reset_index(drop=True, inplace=True)

In [82]:
# as in numpy arrays, we can do element-wise operations on columns of a pandas dataframe. 
df['Engine HP'] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [ ]:
# we can also do comparisons as we did in numpy arrays.
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [83]:
# we can use the comparisons (or more percisely, the logical operators), to filter the data in a dataframe.
df[df['Make'] == "Nissan"]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [ ]:
# we can also combine our conditions with and/or (&, |):
df[(df['Make'] == "Nissan") | (df['Year'] >= 2015)]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [90]:
# pandas supports string operations unlike numpy (numpy is written for numeric calculations).
# to use string methods on pandas columns, we use the .str method:
df['Vehicle_Style'].str.capitalize()

0          Sedan
1          Sedan
2    Convertible
3        4dr suv
4         Pickup
Name: Vehicle_Style, dtype: object

In [ ]:
# we can also use the replace method to transform any space characters to underscores:
df['Vehicle_Style'].str.replace(pat=" ", repl="_")

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [ ]:
# we can also chain these operations to do the changes all together:
df['Vehicle_Style'].str.capitalize().str.replace(pat=" ", repl="_")

0          Sedan
1          Sedan
2    Convertible
3        4dr_suv
4         Pickup
Name: Vehicle_Style, dtype: object

In [93]:
# to save these changes, we can assign the new values to the dataframe.
df['Vehicle_Style'] = df['Vehicle_Style'].str.capitalize().str.replace(pat=" ", repl="_")
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,Sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,Convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [99]:
# as in numpy, we have the summarizing operators(min, max, sum, etc.):
print(df.MSRP.min())
print(df.MSRP.max())
print(df.MSRP.sum())
print(df.MSRP.mean())
print(df.MSRP.median())
print(df.MSRP.std())
print(df.MSRP.var())

2000
54990
150930
30186.0
32340.0
18985.044903818372
360431930.0

In [100]:
# we also have the describe method which provides all the useful information all in one:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [ ]:
# we can also call the describe method on the whole dataframe (calcualte the same information for numeric columns):
df.describe()

              Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [104]:
# we can use the round function to show the numbers rounded untill n decimal points. 
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [106]:
# see the set of values of a column:
df.Make.unique()

array(['Nissan', 'Hyundai', 'Lotus', 'GMC'], dtype=object)

In [107]:
# see the number of unique values in a column:
df.Make.nunique()

4

In [110]:
# to see the null values in the dataframe, we use the isnull() method:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [111]:
# we can use the sum method alongside the isnull method to find out the number of null values in each column:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [113]:
# we can group the data of the dataframe by the values of a certain column using the groupby method:
df.groupby("Transmission Type").MSRP.mean().round(2)

Transmission Type
AUTOMATIC    30800.00
MANUAL       29776.67
Name: MSRP, dtype: float64

In [115]:
# we can access the numpy array of the values using the values method.
np_array_year = df['Year'].values
print(np_array_year)

[1991 2017 2010 2017 2017]